---
title: "BikeSharing_NB_models"
author: "Lorenzo Tonet, Giovanni Oro, Riccardo Samaritan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(corrplot)
library(patchwork)
library(ggplot2)
library(mgcv)
library(ggridges)
library(MASS)
```

```{r data_import}
df = read.csv("hour.csv")
```

```{r summary}
df$season_f = factor(df$season, labels = c("Spring", "Summer", "Autumn","Winter"))
df$weather_f = factor(df$weathersit, labels = c("Clear", "Cloudy/Mist", "Light Snow/Rain", "Heavy Rain"))
df$workday_f = factor(df$workingday, labels = c("Weekend/Holiday", "Working day"))
df$hr_f = factor(df$hr)
df$weekday_f = factor(df$weekday)
df$yr_f = factor(df$yr, labels = c("2011","2012"))

levels(df$weather_f)[levels(df$weather_f) == "Heavy Rain"] = "Light Snow/Rain"
df$weather_f = droplevels(df$weather_f)
table(df$weather_f)
```


```{r train test split}
set.seed(6767)

train_id = sample(1:nrow(df), 0.75*nrow(df))
train = df[train_id, ]
test  = df[-train_id, ]
```


```{r baseline}
baseline_LineReg = lm(cnt ~ 
      hr +
      season_f +
      workday_f +
      weather_f +
      temp +
      yr_f +
      hum +
      windspeed,
      data = train)

summary(baseline_LineReg)
```

---
```{r negative_binomial_reg_full}
mod_nb_full = glm.nb(cnt ~ 
      hr_f +
      season_f +
      yr_f +
      workday_f +
      weather_f +
      temp +
      hum +
      windspeed +
      season_f*weather_f +
      hr_f*workday_f,
      data = train)

summary(mod_nb_full)
```

```{r dispersion in nb}
deviance(mod_nb_full) / df.residual(mod_nb_full) # close to 1 --> good
``` 

```{r negative_binomial_reg_best_poiss}
mod_nb_hr_working = glm.nb(cnt ~ 
      hr_f +
      season_f +
      yr_f +
      workday_f +
      weather_f +
      temp +
      hr_f*workday_f,
      data = train)

mod_nb_season_weather = glm.nb(cnt ~ 
      hr_f +
      season_f +
      yr_f +
      workday_f +
      weather_f +
      temp +
      season_f*weather_f,
      data = train)

mod_nb_no_interactions = glm.nb(cnt ~ 
      hr_f +
      season_f +
      yr_f +
      workday_f +
      weather_f +
      temp + 
      hum +
      windspeed,
      data = train)

```

```{r dispersion in nb}
deviance(mod_nb_hr_working) / df.residual(mod_nb_hr_working) # close to 1 --> good
``` 
```{r aic}
AIC(mod_nb_full, mod_nb_hr_working, mod_nb_season_weather, mod_nb_no_interactions)
```
```{r nested model test}
anova(mod_nb_hr_working, mod_nb_full)
```
```{r final model}
summary(mod_nb_hr_working)
```
```{r}
plot(mod_nb_hr_working)
```